basePath: /
definitions:
  types.ErrorResponse:
    properties:
      errorMessage:
        type: string
    type: object
  types.ResponseWeatherInfo:
    properties:
      region:
        type: string
      temp:
        type: string
      weather:
        type: string
    type: object
host: localhost:8000
info:
  contact: {}
  description: API server for weatherchecker Application
  title: Weatherchecker
  version: "1.0"
paths:
  /getweatherinfo:
    get:
      consumes:
      - application/json
      description: weathercheck
      operationId: weathercheck
      parameters:
      - description: address
        in: query
        name: address
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.ResponseWeatherInfo'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/types.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/types.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/types.ErrorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/types.ErrorResponse'
      summary: weathercheck
      tags:
      - weathercheck
swagger: "2.0"
